[package]
name = "tet-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = "0.19"
crossterm = "0.25"
clap = { version = "4.1.4", features = ["derive"] }
envy = "0.4"
serde = { version = "1.0", features = ["derive"] }
