[package]
name = "tet-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = "0.19"
crossterm = "0.25"
clap = { version = "4.1.4", features = ["derive", "env", "cargo", "string"] }
toml = "0.5.2"
serde = { version = "1.0", features = ["derive"] }
dirs = "4.0"
